apiVersion: apps/v1
kind: Deployment
metadata:
  name: javapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javapp
  template:
    metadata:
      labels:
        app: javapp
    spec:
      containers:
        - name: javapp
          image: likhi1/restaurantproject:latest
          ports:
            - containerPort: 8081
