version: "3.8"
services:
 postgres:
   image: postgres:latest
   container_name: postgres_db
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: Likhi@321
     POSTGRES_DB:SPRINT
   volumes:
     - postgres-data:/var/lib/postgresql/data
 app:
   build: .
   container_name: myapplication
   depends_on:
     - postgres
   environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SPRINT
     SPRING_DATASOURCE_USERNAME: postgres
     SPRING_DATASOURCE_PASSWORD:  Likhi@321
   ports:
     - "8080:8080"
volumes:
 postgres-data:
